export const students = [
	{
		Name: 'Aashutosh Acharya',
		'Father name': 'Prashant',
		'Roll no.': '101',
		'student ID': '8756941',
		Category: 'General',
		'Date of Birth': '10-10-2001',
		Gender: 'Male',
	},
	{
		Name: 'Abhimanyu',
		'Father name': 'Adi shankar',
		'Roll no.': '102',
		'student ID': '8756934',
		Category: 'OBC',
		'Date of Birth': '8-10-2001',
		Gender: 'Male',
	},
	{
		Name: 'Arjun',
		'Father name': 'Amrendra',
		'Roll no.': '103',
		'student ID': '8659348',
		Category: 'Genral',
		'Date of Birth': '19-10-2001',
		Gender: 'Male',
	},
	{
		Name: 'Bhushan',
		'Father name': 'Anant Maurya',
		'Roll no.': '104',
		'student ID': '8669456',
		Category: 'ST',
		'Date of Birth': '19-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Druv',
		'Father name': 'Ashwatthama',
		'Roll no.': '105',
		'student ID': '8698956',
		Category: 'General',
		'Date of Birth': '19-8-2001',
		Gender: 'Male',
	},
	{
		Name: 'Gaurav',
		'Father name': 'Dhananjay',
		'Roll no.': '106',
		'student ID': '8753968',
		Category: 'General',
		'Date of Birth': '29-7-2001',
		Gender: 'Male',
	},
	{
		Name: 'Gulshan',
		'Father name': 'Dhirendra',
		'Roll no.': '107',
		'student ID': '8756471',
		Category: 'General',
		'Date of Birth': '6-9-2001',
		Gender: 'Male',
	},
	{
		Name: 'Harish',
		'Father name': 'Budh Dev',
		'Roll no.': '108',
		'student ID': '8701453',
		Category: 'General',
		'Date of Birth': '16-9-2001',
		Gender: 'Male',
	},
	{
		Name: 'Eklavya',
		'Father name': 'Durvasa',
		'Roll no.': '109',
		'student ID': '8756945',
		Category: 'General',
		'Date of Birth': '26-9-2001',
		Gender: 'Male',
	},
	{
		Name: 'Nikhar',
		'Father name': 'Kanishka',
		'Roll no.': '110',
		'student ID': '8569566',
		Category: 'General',
		'Date of Birth': '23-9-2001',
		Gender: 'Male',
	},
	{
		Name: 'Parth',
		'Father name': 'Kripacharya',
		'Roll no.': '111',
		'student ID': '8654355',
		Category: 'General',
		'Date of Birth': '23-10-2001',
		Gender: 'Male',
	},
	{
		Name: 'Preetam',
		'Father name': 'Mahendra',
		'Roll no.': '112',
		'student ID': '8756956',
		Category: 'BC',
		'Date of Birth': '29-10-2001',
		Gender: 'female',
	},
	{
		Name: 'Puroshotam',
		'Father name': 'Parshuram',
		'Roll no.': '113',
		'student ID': '8565965',
		Category: 'BC',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Rudra',
		'Father name': 'Pramatma Das',
		'Roll no.': '114',
		'student ID': '8796483',
		Category: 'General',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Shashank',
		'Father name': 'Prithvi Nath',
		'Roll no.': '115',
		'student ID': '8656965',
		Category: 'General',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Shudhanshu',
		'Father name': 'Rajiv Dixit',
		'Roll no.': '116',
		'student ID': '8865953',
		Category: 'St',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Siddharth',
		'Father name': 'Vibhishana',
		'Roll no.': '117',
		'student ID': '9563456',
		Category: 'General',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Vaibhav',
		'Father name': 'Vishrava',
		'Roll no.': '118',
		'student ID': '8723994',
		Category: 'General',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
	{
		Name: 'Yudhisthir',
		'Father name': 'Vishwamitra',
		'Roll no.': '119',
		'student ID': '8463295',
		Category: 'General',
		'Date of Birth': '29-5-2001',
		Gender: 'Male',
	},
];

export const aliasMap = {
	Name: ['name', 'full name'],
	'Father name': ['father', 'father name', 'dad', 'fathername'],
	'Mother name': ['mother name', 'mom', "mother's name"],
	'Date of Birth': [
		'dob',
		'date of birth',
		'birth',
		'birthdate',
		'dateofbirth',
	],
	'student ID': ['id', 'student id'],
	Gender: ['gender', 'gen', 'sex'],
	Category: ['category', 'caste', 'group', 'social group'],
	'Roll no.': ['roll', 'roll no', 'roll number'],
};

export const fieldTypes = {
	Name: 'text',
	'Father name': 'text',
	'Date of Birth': 'text',
	'student ID': 'text',
	Gender: 'option',
	Category: 'option',
	'Roll no.': 'text',
};
